### ISSUE TITLE
[Crash] NullPointerException in the mod

### ISSUE THREAD

**Issue by Sunconure11** [satyrnidae/wolfarmor#46] opened 2018-08-30 12:57 UTC
https://pastebin.com/Qnutna2c

Unsure as how to replicate this, but I have been reporting all errors I find in my modpack as of late for stability.

**Comment by IdrisQe** [comment] 2018-09-03 10:41
I have a null pointer issue as well. Vanillafix detects it and proceeds to spam error logs from the wolf armor mod "crash" happening over and over the moment I disconnect from my server through the disconnect button (timing out, server closing, etc. do not cause this issue for some reason.) It persists even if I load back into the server, only closing and re-opening Minecraft entirely seems to fix it.
[crash-2018-09-03_01.01.59-client.txt](https://github.com/CenturionFox/wolfarmor/files/2345212/crash-2018-09-03_01.01.59-client.txt)

**Comment by gsbaoge** [comment] 2018-12-21 08:02
It seems the capability's DataParameter object doesn't initialized at the suitable position.
If another mod create their entity just inherited from the EntityWolf, and also create them own DataParameter . it will cause this problem.
To solve it, you must wrote a class transformer to inject the code at EntityWolf.<clinit>(),
and initialize the HAS_CHEST and ARMOR_ITEM at there.

**Comment by O13SC3N3** [comment] 2019-04-14 14:27
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1087)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3941)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException
    at com.attributestudios.wolfarmor.common.network.packets.WolfArmorCapabilityDataMessage.process(WolfArmorCapabilityDataMessage.java:47)
    at com.attributestudios.wolfarmor.common.network.MessageBase$1.run(MessageBase.java:46)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 17 more

Even on a single player enviroment, seems like exiting the current save throws this about 50/50 of the time. Not sure if this really causes any true issues, but it will crash the client.

**Closed** 2019-06-02 20:36 UTC
Labels: bug
