### ISSUE TITLE
[1.12.2] Compilation produces deobf jar

### ISSUE THREAD

**Issue by Brycey92** [satyrnidae/wolfarmor#103] opened 2020-07-27 16:41 UTC
**Issue Description**
When I try to compile this manually on the 1.12 branch, after commenting out signJar, compilation produces a deobfuscated jar.

**Reproduction Steps**
1. Comment out signJar everywhere it appears in build.gradle
2. Add signJar's dependencies back to the dependency chain
3. Run gradlew build
4. Attempt to place armor on a tamed wolf
5. Game crashes with an error stating a certain deobf function can't be found.

**Expected Behavior**
Compilation should reobfuscate references to Minecraft code before creating the jar files

**Version Information:**
 - OS: Windows 7
 - Java: Java 8
 - Minecraft Version: 1.12.2
 - Mod Version: From commit 6c4b6db817e0bcc9a76d58a1aca6f25c53101f09

**Comment by satyrnidae** [comment] 2020-08-16 03:36
I'm unable to reproduce the issue in the latest version. I suspect that my recent update of the build.gradle toolchain has incidentally fixed it.  Additionally as of 17282c955d5c519ba47c941a2ce8eda2b1fb6f28 you shouldn't need to comment out signJar; it'll be skipped and still allow you to build if no keyStore is specified. (That specific commit still has some issues, because I'm still not great w/ Gradle.  I would recommend using b4194943e78144e846b62fd28ed4a9c432dec5eb.)

I recently had issues w/ merging a feature branch into versions/1.12 and had to re-create the branch.  I've also added some branch protection rules and a CI build to catch weird issues before they get merged.  As for your fork, you may want to try [rebasing your branches on upstream](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a).

Please note that the latest version has several changes to configuration & no config GUI yet, so if you want to test specific features you'll have to edit the file manually.

I'm going to close this investigation as fixed.  Let me know if you still have issues after the rebase; I can re-open then if you do.

**Closed by satyrnidae** 2020-08-16 03:36 UTC
Labels: investigation

**Comment by satyrnidae** [comment] 2020-08-16 21:34
see #109 
i figured it out, the issue might be that the API wasn't properly reobfuscated. Fixed in v3.6.2.
Thanks!

**Comment by Brycey92** [comment] 2020-08-28 01:03
Thanks for the fixes, and thanks for the tips too!

> 
> 
> As for your fork, you may want to try [rebasing your branches on upstream](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a).

Luckily, a fix to #104 was all I was working on, but you've beaten me to it! I'll start a new fork next time I'm trying to add or change something.

Keep up the good work :smile:
